version: "3.11"

services:
  fastapi:
    image: crypto_fastapi
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
